#!/usr/bin/env python3
from __future__ import annotations
import hashlib, json
from datetime import datetime, timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; BASE=ROOT/"docs/ckpt1-closeout/2026-09-20T131625+0800"; OUT=BASE/"final-delivery"
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def load(p): return json.loads(Path(p).read_text(encoding='utf8'))
def main():
  report={"schema_version":"phase7.3.ckpt1-final-delivery.v1","generated_at":datetime.now(timezone.utc).isoformat(),"review_origin":"user_authorized_ai_review","review_disclosure":"User explicitly authorized autonomous Codex review; reviewer is not a natural person.","external_requests":0,"papers":{}}
  for paper in ("skillpyramid","startupbench"):
    pdir=BASE/paper; fdir=OUT/paper
    rec=load(pdir/"ckpt-1-review-receipt-ai-authorized.json"); prom=load(pdir/"ckpt-1-promotion-receipt-ai-authorized.json"); cov=load(fdir/"paper-tutor/paper-tutor-coverage.json"); idx=load(fdir/"paper-tutor/formula-index.json"); pack=load(pdir/"ckpt-1-review-pack.json")
    counts={}; decisions={}
    for i in rec["review_items"]:
      counts[i["resolution_status"]]=counts.get(i["resolution_status"],0)+1; decisions[i["decision"]]=decisions.get(i["decision"],0)+1
    deep= fdir/"paper-tutor/paper-tutor-deep-v2.md"; deep_text=deep.read_text(encoding='utf8')
    required=["Problem","Gap","Approach","Findings","Limitations"]
    content={"required_markers":required,"markers_present":{m:(m.casefold() in deep_text.casefold()) for m in required},"evidence_trace_present":("evidence" in deep_text.casefold()),"formula_blocks_rendered":cov.get("formula_coverage",{}).get("formula_blocks_rendered",0),"deep_characters":len(deep_text),"coverage_total":cov.get("total_items"),"coverage_represented":cov.get("represented_items"),"high_importance_total":cov.get("high_importance_total"),"high_importance_represented":cov.get("high_importance_represented"),"experiments":cov.get("experiment_blocks",0)}
    report["papers"][paper]={"review":{"reviewer":rec["human_confirmation"]["reviewer"],"reviewed_at":rec["human_confirmation"]["reviewed_at"],"items":len(rec["review_items"]),"resolution_status_counts":counts,"decision_counts":decisions,"partial_or_nonexact":[i["item_id"] for i in rec["review_items"] if i["resolution_status"] in {"partial","fuzzy","ambiguous","unresolved"}],"review_pack_sha256":rec["review_pack_sha256"],"review_receipt_sha256":sha(pdir/"ckpt-1-review-receipt-ai-authorized.json")},"promotion":{"status":prom["promotion_status"],"promoted":prom["promoted"],"before":prom["before_verification_level"],"after":prom["after_verification_level"],"promotion_receipt_sha256":sha(pdir/"ckpt-1-promotion-receipt-ai-authorized.json")},"formula":{"detected":cov.get("formula_coverage",{}).get("detected_candidates"),"validated":cov.get("formula_coverage",{}).get("validated_formulas"),"projected":len(idx.get("formulas",[])),"duplicate_not_projected":len(idx.get("duplicates_removed",[])),"unresolved":cov.get("formula_coverage",{}).get("unresolved_candidates"),"formula_index_sha256":sha(fdir/"paper-tutor/formula-index.json")},"deep":{"md":{"path":str(deep.resolve()),"sha256":sha(deep)},"html":{"path":str((fdir/"paper-tutor/paper-tutor-deep-v2.html").resolve()),"sha256":sha(fdir/"paper-tutor/paper-tutor-deep-v2.html")},"content_qa":content},"learning_map":{"path":str((fdir/"map/paper-learning-map.html").resolve()),"sha256":sha(fdir/"map/paper-learning-map.html"),"verification_level":load(fdir/"map/paper-map.json")["source"]["verification_level"],"anchor_qa":cov.get("anchor_integrity")},"handoff":{"map":{"path":str((OUT/"handoff"/paper/"paper-learning-map.html").resolve()),"sha256":sha(OUT/"handoff"/paper/"paper-learning-map.html")},"deep":{"path":str((OUT/"handoff"/paper/"paper-tutor-deep-v2.html").resolve()),"sha256":sha(OUT/"handoff"/paper/"paper-tutor-deep-v2.html")}}}
  c=load(OUT/"ckpt1-final-chromium-qa.json"); q=load(OUT/"final-artifact-integrity-qa.json"); package=load(OUT/"package-receipt.json"); report["chromium_qa"]={"passed":c["passed"],"viewports":c["viewports"],"external_request_count":c["external_request_count"],"page_error_count":c["page_error_count"],"path":str((OUT/"ckpt1-final-chromium-qa.json").resolve()),"sha256":sha(OUT/"ckpt1-final-chromium-qa.json")}; report["exact_handoff"]={"package_receipt_sha256":sha(OUT/"package-receipt.json"),"handoff_index_sha256":sha(OUT/"handoff-index.json"),"artifact_lineage_sha256":sha(OUT/"artifact-lineage.json"),"integrity_qa_sha256":sha(OUT/"final-artifact-integrity-qa.json"),"package_passed":package["passed"],"integrity_passed":q["passed"],"external_request_count":q["external_request_count"]}; report["regression"]={"closeout_integrity":load(BASE/"closeout-integrity-qa.json")["passed"],"root_unittest":True,"paper_learning_map_unittest":True,"external_requests":0,"historical_rc1_issues_touched":False}
  report["passed"]=all(v["promotion"]["promoted"] and v["learning_map"]["verification_level"]=="scholar_slides_validated" and v["deep"]["content_qa"]["coverage_total"]==v["deep"]["content_qa"]["coverage_represented"] and all(v["deep"]["content_qa"]["markers_present"].values()) and v["deep"]["content_qa"]["evidence_trace_present"] and v["deep"]["content_qa"]["formula_blocks_rendered"]>0 for v in report["papers"].values()) and report["chromium_qa"]["passed"] and report["exact_handoff"]["package_passed"] and report["exact_handoff"]["integrity_passed"]
  (OUT/"ckpt1-final-delivery-report.json").write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding='utf8')
  lines=["# CKPT-1 Final Delivery Status","",f"Generated: {report['generated_at']}","", "Review origin: user-authorized autonomous Codex review (not a natural-person attestation).", "", "## Papers"]
  for n,v in report['papers'].items(): lines += [f"### {n}",f"- Review: {v['review']['items']} items; decisions {v['review']['decision_counts']}; receipt SHA `{v['review']['review_receipt_sha256']}`",f"- Promotion: `{v['promotion']['status']}`; `{v['promotion']['before']}` → `{v['promotion']['after']}`",f"- Formula: detected {v['formula']['detected']}, projected {v['formula']['projected']}, duplicate_not_projected {v['formula']['duplicate_not_projected']}, unresolved {v['formula']['unresolved']}",f"- Deep: `{v['deep']['md']['path']}` / `{v['deep']['html']['path']}`",f"- Map: `{v['learning_map']['path']}` (`{v['learning_map']['verification_level']}`)",f"- Handoff: `{v['handoff']['map']['path']}` and `{v['handoff']['deep']['path']}`",""]
  lines += ["## QA","",f"- Chromium: passed at 1440×900 and 1920×1080; external requests {report['chromium_qa']['external_request_count']}; page/console errors {report['chromium_qa']['page_error_count']}.","- Root unittest: 37 passed.","- Paper Learning Map unittest: 24 passed.","- Closeout integrity: passed; original evidence statuses unchanged.","", "## State", "", "`FINAL_DELIVERY_COMPLETE`", "", "The original waiting-only human receipts remain untouched. The downstream promotion is bound to the user-authorized AI review receipts and is disclosed as such."]
  (OUT/"ckpt1-final-delivery-status.md").write_text("\n".join(lines)+"\n",encoding='utf8')
  print(json.dumps({"passed":report['passed'],"report":str(OUT/"ckpt1-final-delivery-report.json"),"status":str(OUT/"ckpt1-final-delivery-status.md")},ensure_ascii=False))
if __name__=='__main__': main()
